[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
# we still use serde_cbor for packed CBOR format
ignore = ["RUSTSEC-2021-0127"]

[licenses]
allow = [
    "Apache-2.0",
    "GPL-3.0-or-later",
    "MIT",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "BSD-2-Clause",
    "BSD-3-Clause"
]
